### ISSUE TITLE
Bug modal close on esc if suggestion is active

### ISSUE THREAD

**Issue by yaroslavmo** [softwareplanet/leadboard#124]
steps to reproduce:
-open modal
-start typing that auto completion activates

-press ESC button 

expected result: auto completion is closed, input is cleared and stays active
![image](https://user-images.githubusercontent.com/40685592/44722311-5b38b880-aad5-11e8-8778-0003089d1035.png)

current result: Modal window is closed
![image](https://user-images.githubusercontent.com/40685592/44722329-655ab700-aad5-11e8-9b47-0d807af63bcc.png)

**Comment by valentyntu** [comment]
Fixed in #192
